print("--------> MATRICES AND DETERMINANT.D<--------")
print("------------------> MENU <-------------------")
print("finding determinant of a 2x2 matrix? click 1")
print("finding determinant of a 3x3 matrix? click 2")
print("multiplication matrix of 2x2? click 3")
print("multiplication matrix of 3x3? click 4")
print("inverse of 2x2 matrix? click 5")
print("inverse of 3x3 matrix? click 6")
print("quit? click 7")
print("---------------------------------------------")

while True:
    choice = int(input("Enter your choice: "))
    if choice == 1:
         print("| a  b |")
         print("| c  d |")
         print("---------------------------------------------")
         print("Enter the elements of a 2x2 matrix")
         a = int(input("Enter the element a: "))
         b = int(input("Enter the element b: "))
         c = int(input("Enter the element c: "))
         d = int(input("Enter the element d: "))
         det2 = a*d - b*c
         print("| ", a," ", b, " |")
         print("| ", c," ", d, " |")
         print("The determinant of the matrix is: ", det2)
    elif choice == 2:
        print("| a  b  c |")
        print("| d  e  f |")
        print("| g  h  i |")
        print("Enter the elements of a 3x3 matrix")
        a = int(input("Enter the element a: "))
        b = int(input("Enter the element b: "))
        c = int(input("Enter the element c: "))
        d = int(input("Enter the element d: "))
        e = int(input("Enter the element e: "))
        f = int(input("Enter the element f: "))
        g = int(input("Enter the element g: "))
        h = int(input("Enter the element h: "))
        i = int(input("Enter the element i: "))
        det3 = a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)
        print("| ", a, b, c, " |")
        print("| ", d, e, f, " |")
        print("| ", g, h, i, " |")
        print("The determinant of the matrix is: ", det3)  
    elif choice == 3:
        print("for AxB")
        print("METRIX A =")
        print("| A1  A2 |")
        print("| A3  A4 |")
        print("---------------------------------------------")
        print("Enter the elements of matrix A")
        A1 = int(input("Enter the element A1: "))
        A2 = int(input("Enter the element A2: "))
        A3 = int(input("Enter the element A3: "))
        A4 = int(input("Enter the element A4: "))
        print("| ",A1,"  ",A2," |")
        print("| ",A3,"  ",A4," |")
        print("---------------------------------------------")
        print("Enter the elements of matrix B")
        V = input("IS MATRIX B = MATRIX A? (y/n): ")
        if V == "y":
            print("METRIX AxA =")
            print("| ", A1*A1+A2*A3, "  ", A1*A2+A2*A4, " |")
            print("| ", A3*A1+A4*A3, "  ", A3*A2+A4*A4, " |")
        else:
            print("METRIX B =")
            print("| B1  B2 |")
            print("| B3  B4 |")
            print("---------------------------------------------")
            print("Enter the elements of matrix B")
            B1 = int(input("Enter the element B1: "))
            B2 = int(input("Enter the element B2: "))
            B3 = int(input("Enter the element B3: "))
            B4 = int(input("Enter the element B4: "))
            print("| ",B1,"  ",B2," |")
            print("| ",B3,"  ",B4," |")
            print("---------------------------------------------")
            print("METRIX AxB =")
            print("| ", A1*B1+A2*B3, "  ", A1*B2+A2*B4, " |")
            print("| ", A3*B1+A4*B3, "  ", A3*B2+A4*B4, " |")
    elif choice == 4:
        print("METRIX A =")
        print("| A1  A2  A3 |")
        print("| A4  A5  A6 |")
        print("| A7  A8  A9 |")
        print("---------------------------------------------")
        print("Enter the elements of matrix A")
        A1 = int(input("Enter the element A1: "))
        A2 = int(input("Enter the element A2: "))
        A3 = int(input("Enter the element A3: "))
        A4 = int(input("Enter the element A4: "))
        A5 = int(input("Enter the element A5: "))
        A6 = int(input("Enter the element A6: "))
        A7 = int(input("Enter the element A7: "))
        A8 = int(input("Enter the element A8: "))
        A9 = int(input("Enter the element A9: "))
        print("| ",A1,"  ",A2,"  ",A3," |")
        print("| ",A4,"  ",A5,"  ",A6," |")
        print("| ",A7,"  ",A8,"  ",A9," |")
        print("---------------------------------------------")
        print("Enter the elements of matrix B")
        V = input("IS MATRIX B = MATRIX A? (y/n): ")
        if V == "y":
            print("METRIX AxA =")
            print("| ", A1*A1+A2*A4+A3*A7, "  ", A1*A2+A2*A5+A3*A8, "  ", A1*A3+A2*A6+A3*A9, " |")
            print("| ", A4*A1+A5*A4+A6*A7, "  ", A4*A2+A5*A5+A6*A8, "  ", A4*A3+A5*A6+A6*A9, " |")
            print("| ", A7*A1+A8*A4+A9*A7, "  ", A7*A2+A8*A5+A9*A8, "  ", A7*A3+A8*A6+A9*A9, " |")
        else:
            print("METRIX B =")
            print("| B1  B2  B3 |")
            print("| B4  B5  B6 |")
            print("| B7  B8  B9 |")
            print("---------------------------------------------")
            print("Enter the elements of matrix B")
            B1 = int(input("Enter the element B1: "))
            B2 = int(input("Enter the element B2: "))
            B3 = int(input("Enter the element B3: "))
            B4 = int(input("Enter the element B4: "))
            B5 = int(input("Enter the element B5: "))
            B6 = int(input("Enter the element B6: "))
            B7 = int(input("Enter the element B7: "))
            B8 = int(input("Enter the element B8: "))
            B9 = int(input("Enter the element B9: "))
            print("| ",B1,"  ",B2,"  ",B3," |")
            print("| ",B4,"  ",B5,"  ",B6," |")
            print("| ",B7,"  ",B8,"  ",B9," |")
            print("---------------------------------------------")
            print("METRIX AxB =")
            print("| ",A1*B1+A2*B4+A3*B7,"  ",A1*B2+A2*B5+A3*B8,"  ",A1*B3+A2*B6+A3*B9," |")
            print("| ",A4*B1+A5*B4+A6*B7,"  ",A4*B2+A5*B5+A6*B8,"  ",A4*B3+A5*B6+A6*B9," |")
            print("| ",A7*B1+A8*B4+A9*B7,"  ",A7*B2+A8*B5+A9*B8,"  ",A7*B3+A8*B6+A9*B9," |")
    elif choice == 5:
        print("METRIX A =")
        print("| A1  A2 |")
        print("| A3  A4 |")
        print("---------------------------------------------")
        print("Enter the elements of matrix A")
        A1 = int(input("Enter the element A1: "))
        A2 = int(input("Enter the element A2: "))
        A3 = int(input("Enter the element A3: "))
        A4 = int(input("Enter the element A4: "))
        print("---------------------------------------------")
        det2 = A1*A4 - A2*A3
        print("1 ","| ", A4,"  ", -A2, " |")
        print("__","| ", -A3,"  ", A1, " |")
        print(det2)
    elif choice == 6:
        print("METRIX A =")
        print("| A1  A2  A3 |")
        print("| A4  A5  A6 |")
        print("| A7  A8  A9 |")
        print("---------------------------------------------")
        print("Enter the elements of matrix A") 
        A1 = int(input("Enter the element A1: "))
        A2 = int(input("Enter the element A2: "))   
        A3 = int(input("Enter the element A3: "))
        A4 = int(input("Enter the element A4: "))
        A5 = int(input("Enter the element A5: "))
        A6 = int(input("Enter the element A6: "))
        A7 = int(input("Enter the element A7: "))
        A8 = int(input("Enter the element A8: "))
        A9 = int(input("Enter the element A9: "))
        print("---------------------------------------------")
        det3 = A1*(A5*A9 - A6*A8) - A2*(A4*A9 - A6*A7) + A3*(A4*A8 - A5*A7)
        print("1 ","| ", (A5*A9 - A6*A8) ,"  ",(-1)* (A2*A9 - A3*A8), "  ", (A2*A6 - A3*A5), " |")
        print("__","| ",(-1)*(A4*A9 - A6*A7) ,"  ", (A1*A9 - A3*A7), "  ",(-1)*(A1*A6 - A3*A4), " |") 
        print(det3,"| ", (A4*A8 - A5*A7) ,"  ", (-1)*(A1*A8 - A2*A7), "  ", (A1*A5 - A2*A4), " |")    
    elif choice == 7:
            print("program terminated! thanks")
            break
    m=input("want to do more operations? (y/n): ")
    if m == "n":
        break
    else:
        continue

